version: 1
from: "infracamp/kickstart-flavor-gaia:testing"

apache_fallback_resource: "/index.php"

command:
  build:
    - "composer update"
    - "cd /opt/lib && ./install-urdsfmt.sh"

  test:
    - "vendor/bin/phpunit"
